apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"backend-service","namespace":"default"},"spec":{"ports":[{"nodePort":30080,"port":80,"targetPort":3000}],"selector":{"app":"backend"},"type":"NodePort"}}
  name: backend-service
  namespace: default
spec:
  clusterIP: 10.43.120.7
  clusterIPs:
    - 10.43.120.7
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: backend
  sessionAffinity: None
  type: NodePort
