apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cloudifyrides
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: backend
  sessionAffinity: None
  type: NodePort
