apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backend","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"backend"}},"template":{"metadata":{"labels":{"app":"backend"}},"spec":{"containers":[{"env":[{"name":"DATA_FILE","value":"/data/rides.db"}],"image":"jsbowen79/cloudifyrides-backend:v6","imagePullPolicy":"IfNotPresent","name":"backend","ports":[{"containerPort":3000}],"readinessProbe":{"httpGet":{"path":"/rides","port":3000},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/data","name":"rides-data"}]}],"initContainers":[{"command":["sh","-c","mkdir -p /data \u0026\u0026 chmod -R 777 /data"],"image":"busybox","name":"init-backend-data-dir","volumeMounts":[{"mountPath":"/data","name":"rides-data"}]}],"volumes":[{"name":"rides-data","persistentVolumeClaim":{"claimName":"rides-pvc"}}]}}}}
  name: backend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: DATA_FILE
              value: /data/rides.db
          image: jsbowen79/cloudifyrides-backend:v6
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /rides
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: rides-data
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sh
            - -c
            - mkdir -p /data && chmod -R 777 /data
          image: busybox
          imagePullPolicy: Always
          name: init-backend-data-dir
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: rides-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: rides-data
          persistentVolumeClaim:
            claimName: rides-pvc
