apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
    - kubernetes.io/pv-protection
  name: rides-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: rides-pvc
    namespace: default
    resourceVersion: "579"
  hostPath:
    path: /mnt/data/rides
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
