name: Terraform Deploy

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -input=false -force-copy

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Terraform Output
        run: terraform output -json

