name: Terraform Taint K3S

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ${{ secrets.TF_VAR_aws_region }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Restore Terraform state
        uses: actions/download-artifact@v3
        with:
          name: terraform-state
          path: .


      - name: Terraform Init
        run: terraform init

      - name: Taint k3s_node instance
        run: terraform taint aws_instance.k3s_node

      - name: Terraform Apply
        env:
          TF_LOG: DEBUG
        run: terraform apply -auto-approve -input=false
        continue-on-error: false

      - name: Save Terraform state
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: terraform.tfstate



      - name: Terraform Output
        run: terraform output -json

